package com.augment.acmeshop.models;

import android.annotation.SuppressLint;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Copyright © 2016-present Augment. All rights reserved.
 */

/**
 * This is the Fake data that we use to populate the app
 * It has to be init once
 */
public class Data {

    @SuppressLint("UseSparseArrays")
    static Map<Integer, Category> categories = new HashMap<>();
    @SuppressLint("UseSparseArrays")
    static Map<Integer, Product> products = new HashMap<>();
    @SuppressLint("UseSparseArrays")
    static Map<Integer, List<Integer>> products_categories = new HashMap<>();

    public static void init() {
        if (categories.size() > 0) {
            return;
        }

        categories.put(1, new Category(1, "Home Appliance", "category_homeappliance"));
        categories.put(2, new Category(2, "Laptops", "category_laptop"));
        categories.put(3, new Category(3, "Mobile Phones", "category_phone"));
        categories.put(4, new Category(4, "Portable Speakers", "category_speakers"));
        categories.put(5, new Category(5, "TV", "category_tv"));

        products.put(1,  new Product(1,  "3700342425321", "AIR", "Force Extreme", "airforceextreme", 179.99, "Duis rhoncus id neque non varius. Phasellus tristique, lorem vel bibendum dictum, orci erat pharetra mi, sit amet dapibus lectus lorem eget est. Mauris consectetur blandit tortor, eu pulvinar mi tempor quis. Vivamus purus sapien, bibendum a nisl consequat, condimentum vestibulum nisi. In hac habitasse platea dictumst. Vivamus nec orci dictum, iaculis lorem et, sollicitudin lacus. Morbi venenatis felis tristique egestas semper. Curabitur at risus cursus, maximus odio vitae, faucibus turpis. Nullam et tristique lacus, sit amet ullamcorper nibh. Nulla quis maximus dolor. Nulla tincidunt nibh tellus. Donec mauris nisi, congue at aliquet at, blandit sit amet nulla. Etiam quis ligula fringilla, finibus lorem vel, maximus mauris."));
        products.put(2,  new Product(2,  "0017817704656", "Bose", "Soundlink Mini II", "bosesoundlinkminiii", 199.99, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In accumsan a augue pulvinar mollis. Sed et ullamcorper sem, eget accumsan sem. Donec ac leo at lacus sagittis tincidunt. Donec sagittis quam diam, a tempor eros interdum malesuada. Vestibulum sagittis sem ac neque cursus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non dictum turpis. Sed venenatis, dolor sed egestas congue, urna ipsum fringilla ex, sed convallis velit orci vitae enim. Aliquam odio turpis, pretium id quam id, varius volutpat ipsum. Duis pharetra lacus tellus, non dictum nulla aliquam eget."));
        products.put(3,  new Product(3,  "3045386370108", "Cookeo", "Connect", "cookeoconnect", 319.99, "Nunc aliquam, sapien a placerat imperdiet, turpis metus dapibus nulla, nec molestie est quam id sem. Vestibulum a sem est. Sed tincidunt ipsum ut dapibus pharetra. Quisque iaculis hendrerit odio, eget facilisis sem consequat non. Phasellus tempus, lorem in blandit viverra, odio mauris tempus lorem, ut lacinia quam velit non nulla. Aliquam ac eleifend arcu. Fusce sem elit, tincidunt et pharetra quis, tempor in purus. Aenean eget viverra ante. Suspendisse maximus mi eget eros porta, eget varius mauris consequat. Nunc blandit lectus et mi rutrum lobortis. Proin rhoncus, lectus nec luctus tristique, sem libero facilisis diam, sed aliquam ante leo a ex."));
        products.put(4,  new Product(4,  "0888462368285", "Apple", "iPad Mini4", "ipadmini", 339.99, "Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla consequat fermentum luctus. In a urna in magna viverra elementum bibendum eget metus. Curabitur metus dolor, congue quis tellus nec, ultricies iaculis turpis. Nunc tristique convallis dui, nec fringilla sem tempus ac. In mattis ac nisl eu egestas. Ut sodales odio id mollis commodo. Nullam justo nibh, vehicula ut purus sed, efficitur commodo ligula. Nunc faucibus dapibus turpis vel iaculis."));
        products.put(5,  new Product(5,  "0888462735605", "Apple", "iPhone SE", "iphonese", 659.99, "Nunc aliquam, sapien a placerat imperdiet, turpis metus dapibus nulla, nec molestie est quam id sem. Vestibulum a sem est. Sed tincidunt ipsum ut dapibus pharetra. Quisque iaculis hendrerit odio, eget facilisis sem consequat non. Phasellus tempus, lorem in blandit viverra, odio mauris tempus lorem, ut lacinia quam velit non nulla. Aliquam ac eleifend arcu. Fusce sem elit, tincidunt et pharetra quis, tempor in purus. Aenean eget viverra ante. Suspendisse maximus mi eget eros porta, eget varius mauris consequat. Nunc blandit lectus et mi rutrum lobortis. Proin rhoncus, lectus nec luctus tristique, sem libero facilisis diam, sed aliquam ante leo a ex."));
        products.put(6,  new Product(6,  "0050036326438", "JBL", "Charge 2 plus", "jblchargeplus", 129.99, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In accumsan a augue pulvinar mollis. Sed et ullamcorper sem, eget accumsan sem. Donec ac leo at lacus sagittis tincidunt. Donec sagittis quam diam, a tempor eros interdum malesuada. Vestibulum sagittis sem ac neque cursus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non dictum turpis. Sed venenatis, dolor sed egestas congue, urna ipsum fringilla ex, sed convallis velit orci vitae enim. Aliquam odio turpis, pretium id quam id, varius volutpat ipsum. Duis pharetra lacus tellus, non dictum nulla aliquam eget."));
        products.put(7,  new Product(7,  "0050036327350", "JBL", "Pulse 2", "jblpulse", 159.99, "Duis rhoncus id neque non varius. Phasellus tristique, lorem vel bibendum dictum, orci erat pharetra mi, sit amet dapibus lectus lorem eget est. Mauris consectetur blandit tortor, eu pulvinar mi tempor quis. Vivamus purus sapien, bibendum a nisl consequat, condimentum vestibulum nisi. In hac habitasse platea dictumst. Vivamus nec orci dictum, iaculis lorem et, sollicitudin lacus. Morbi venenatis felis tristique egestas semper. Curabitur at risus cursus, maximus odio vitae, faucibus turpis. Nullam et tristique lacus, sit amet ullamcorper nibh. Nulla quis maximus dolor. Nulla tincidunt nibh tellus. Donec mauris nisi, congue at aliquet at, blandit sit amet nulla. Etiam quis ligula fringilla, finibus lorem vel, maximus mauris."));
        products.put(8,  new Product(8,  "8806087217100", "LG", "55EG960V", "lgegv", 1669.99, "Nunc aliquam, sapien a placerat imperdiet, turpis metus dapibus nulla, nec molestie est quam id sem. Vestibulum a sem est. Sed tincidunt ipsum ut dapibus pharetra. Quisque iaculis hendrerit odio, eget facilisis sem consequat non. Phasellus tempus, lorem in blandit viverra, odio mauris tempus lorem, ut lacinia quam velit non nulla. Aliquam ac eleifend arcu. Fusce sem elit, tincidunt et pharetra quis, tempor in purus. Aenean eget viverra ante. Suspendisse maximus mi eget eros porta, eget varius mauris consequat. Nunc blandit lectus et mi rutrum lobortis. Proin rhoncus, lectus nec luctus tristique, sem libero facilisis diam, sed aliquam ante leo a ex."));
        products.put(9,  new Product(9,  "6068860953717", "Apple", "Macbook Pro", "macbookpro", 1599.99, "Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla consequat fermentum luctus. In a urna in magna viverra elementum bibendum eget metus. Curabitur metus dolor, congue quis tellus nec, ultricies iaculis turpis. Nunc tristique convallis dui, nec fringilla sem tempus ac. In mattis ac nisl eu egestas. Ut sodales odio id mollis commodo. Nullam justo nibh, vehicula ut purus sed, efficitur commodo ligula. Nunc faucibus dapibus turpis vel iaculis."));
        products.put(10, new Product(10, "3016661148095", "Masterchef", "Gourmet", "masterchefgourmet", 199.99, "Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla consequat fermentum luctus. In a urna in magna viverra elementum bibendum eget metus. Curabitur metus dolor, congue quis tellus nec, ultricies iaculis turpis. Nunc tristique convallis dui, nec fringilla sem tempus ac. In mattis ac nisl eu egestas. Ut sodales odio id mollis commodo. Nullam justo nibh, vehicula ut purus sed, efficitur commodo ligula. Nunc faucibus dapibus turpis vel iaculis."));
        products.put(11, new Product(11, "3016661146855", "Moulinex", "Companion", "moulinexcompanion", 699.99, "Nunc aliquam, sapien a placerat imperdiet, turpis metus dapibus nulla, nec molestie est quam id sem. Vestibulum a sem est. Sed tincidunt ipsum ut dapibus pharetra. Quisque iaculis hendrerit odio, eget facilisis sem consequat non. Phasellus tempus, lorem in blandit viverra, odio mauris tempus lorem, ut lacinia quam velit non nulla. Aliquam ac eleifend arcu. Fusce sem elit, tincidunt et pharetra quis, tempor in purus. Aenean eget viverra ante. Suspendisse maximus mi eget eros porta, eget varius mauris consequat. Nunc blandit lectus et mi rutrum lobortis. Proin rhoncus, lectus nec luctus tristique, sem libero facilisis diam, sed aliquam ante leo a ex."));
        products.put(12, new Product(12, "3662734940518", "Nespresso", "Pixie", "nespressopixie", 99.99, "Duis rhoncus id neque non varius. Phasellus tristique, lorem vel bibendum dictum, orci erat pharetra mi, sit amet dapibus lectus lorem eget est. Mauris consectetur blandit tortor, eu pulvinar mi tempor quis. Vivamus purus sapien, bibendum a nisl consequat, condimentum vestibulum nisi. In hac habitasse platea dictumst. Vivamus nec orci dictum, iaculis lorem et, sollicitudin lacus. Morbi venenatis felis tristique egestas semper. Curabitur at risus cursus, maximus odio vitae, faucibus turpis. Nullam et tristique lacus, sit amet ullamcorper nibh. Nulla quis maximus dolor. Nulla tincidunt nibh tellus. Donec mauris nisi, congue at aliquet at, blandit sit amet nulla. Etiam quis ligula fringilla, finibus lorem vel, maximus mauris."));
        products.put(13, new Product(13, "5025232824670", "Panasonic", "TX 65CZ950E", "panasonictxcze", 9999.99, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In accumsan a augue pulvinar mollis. Sed et ullamcorper sem, eget accumsan sem. Donec ac leo at lacus sagittis tincidunt. Donec sagittis quam diam, a tempor eros interdum malesuada. Vestibulum sagittis sem ac neque cursus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non dictum turpis. Sed venenatis, dolor sed egestas congue, urna ipsum fringilla ex, sed convallis velit orci vitae enim. Aliquam odio turpis, pretium id quam id, varius volutpat ipsum. Duis pharetra lacus tellus, non dictum nulla aliquam eget."));
        products.put(14, new Product(14, "8806086511599", "Samsung", "UE 55H6400", "samsungueh", 699.99, "Nunc aliquam, sapien a placerat imperdiet, turpis metus dapibus nulla, nec molestie est quam id sem. Vestibulum a sem est. Sed tincidunt ipsum ut dapibus pharetra. Quisque iaculis hendrerit odio, eget facilisis sem consequat non. Phasellus tempus, lorem in blandit viverra, odio mauris tempus lorem, ut lacinia quam velit non nulla. Aliquam ac eleifend arcu. Fusce sem elit, tincidunt et pharetra quis, tempor in purus. Aenean eget viverra ante. Suspendisse maximus mi eget eros porta, eget varius mauris consequat. Nunc blandit lectus et mi rutrum lobortis. Proin rhoncus, lectus nec luctus tristique, sem libero facilisis diam, sed aliquam ante leo a ex."));
        products.put(15, new Product(15, "3045385736158", "Moulinex", "Toaster Subito", "toastermoulinexsubito", 29.99, "Nunc aliquam, sapien a placerat imperdiet, turpis metus dapibus nulla, nec molestie est quam id sem. Vestibulum a sem est. Sed tincidunt ipsum ut dapibus pharetra. Quisque iaculis hendrerit odio, eget facilisis sem consequat non. Phasellus tempus, lorem in blandit viverra, odio mauris tempus lorem, ut lacinia quam velit non nulla. Aliquam ac eleifend arcu. Fusce sem elit, tincidunt et pharetra quis, tempor in purus. Aenean eget viverra ante. Suspendisse maximus mi eget eros porta, eget varius mauris consequat. Nunc blandit lectus et mi rutrum lobortis. Proin rhoncus, lectus nec luctus tristique, sem libero facilisis diam, sed aliquam ante leo a ex."));
        products.put(16, new Product(16, "8003437261381", "Whirlpool", "FSCR 80421", "whirlpoolfscr80421", 439.99, "Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla consequat fermentum luctus. In a urna in magna viverra elementum bibendum eget metus. Curabitur metus dolor, congue quis tellus nec, ultricies iaculis turpis. Nunc tristique convallis dui, nec fringilla sem tempus ac. In mattis ac nisl eu egestas. Ut sodales odio id mollis commodo. Nullam justo nibh, vehicula ut purus sed, efficitur commodo ligula. Nunc faucibus dapibus turpis vel iaculis."));
        products.put(17, new Product(17, "6438158721470", "Nokia", "Lumia 640", "lumia640", 119.99, "Nunc aliquam, sapien a placerat imperdiet, turpis metus dapibus nulla, nec molestie est quam id sem. Vestibulum a sem est. Sed tincidunt ipsum ut dapibus pharetra. Quisque iaculis hendrerit odio, eget facilisis sem consequat non. Phasellus tempus, lorem in blandit viverra, odio mauris tempus lorem, ut lacinia quam velit non nulla. Aliquam ac eleifend arcu. Fusce sem elit, tincidunt et pharetra quis, tempor in purus. Aenean eget viverra ante. Suspendisse maximus mi eget eros porta, eget varius mauris consequat. Nunc blandit lectus et mi rutrum lobortis. Proin rhoncus, lectus nec luctus tristique, sem libero facilisis diam, sed aliquam ante leo a ex."));
        products.put(18, new Product(18, "6438158744554", "Nokia", "Lumia 550", "lumia550", 99.99, "Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla consequat fermentum luctus. In a urna in magna viverra elementum bibendum eget metus. Curabitur metus dolor, congue quis tellus nec, ultricies iaculis turpis. Nunc tristique convallis dui, nec fringilla sem tempus ac. In mattis ac nisl eu egestas. Ut sodales odio id mollis commodo. Nullam justo nibh, vehicula ut purus sed, efficitur commodo ligula. Nunc faucibus dapibus turpis vel iaculis."));
        products.put(19, new Product(19, "8007842628487", "Indesit", "IWC 5125", "indesitiwc5125", 229.99, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In accumsan a augue pulvinar mollis. Sed et ullamcorper sem, eget accumsan sem. Donec ac leo at lacus sagittis tincidunt. Donec sagittis quam diam, a tempor eros interdum malesuada. Vestibulum sagittis sem ac neque cursus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non dictum turpis. Sed venenatis, dolor sed egestas congue, urna ipsum fringilla ex, sed convallis velit orci vitae enim. Aliquam odio turpis, pretium id quam id, varius volutpat ipsum. Duis pharetra lacus tellus, non dictum nulla aliquam eget."));
        products.put(20, new Product(20, "0888462570350", "Apple", "iPhone 6S PLUS", "iphone6p", 899.99, "Duis rhoncus id neque non varius. Phasellus tristique, lorem vel bibendum dictum, orci erat pharetra mi, sit amet dapibus lectus lorem eget est. Mauris consectetur blandit tortor, eu pulvinar mi tempor quis. Vivamus purus sapien, bibendum a nisl consequat, condimentum vestibulum nisi. In hac habitasse platea dictumst. Vivamus nec orci dictum, iaculis lorem et, sollicitudin lacus. Morbi venenatis felis tristique egestas semper. Curabitur at risus cursus, maximus odio vitae, faucibus turpis. Nullam et tristique lacus, sit amet ullamcorper nibh. Nulla quis maximus dolor. Nulla tincidunt nibh tellus. Donec mauris nisi, congue at aliquet at, blandit sit amet nulla. Etiam quis ligula fringilla, finibus lorem vel, maximus mauris."));
        // Product that is not present in our database
        products.put(21, new Product(21, "3045385736000", "Moulinex", "Toaster Moulinex", "toastermoulinexsubito", 29.99, "Duis rhoncus id neque non varius. Phasellus tristique, lorem vel bibendum dictum, orci erat pharetra mi, sit amet dapibus lectus lorem eget est. Mauris consectetur blandit tortor, eu pulvinar mi tempor quis. Vivamus purus sapien, bibendum a nisl consequat, condimentum vestibulum nisi. In hac habitasse platea dictumst. Vivamus nec orci dictum, iaculis lorem et, sollicitudin lacus. Morbi venenatis felis tristique egestas semper. Curabitur at risus cursus, maximus odio vitae, faucibus turpis. Nullam et tristique lacus, sit amet ullamcorper nibh. Nulla quis maximus dolor. Nulla tincidunt nibh tellus. Donec mauris nisi, congue at aliquet at, blandit sit amet nulla. Etiam quis ligula fringilla, finibus lorem vel, maximus mauris. (manquant)"));

        // Home Appliance
        products_categories.put(1, Arrays.asList(1,2,3,10,11,12,15,16,19,21));
        // Laptops
        products_categories.put(2, Arrays.asList(9,4));
        // Mobiles Phones
        products_categories.put(3, Arrays.asList(4,5,17,18,20));
        // Portable Speakers
        products_categories.put(4, Arrays.asList(2,7,6));
        // TV
        products_categories.put(5, Arrays.asList(8,13,14));
    }
}
